source 'http://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'pg'
gem 'sequel'
gem 'sequel_pg'
gem 'compass'
gem 'coffee-script'
gem 'execjs'
gem 'therubyracer'
gem 'sprockets'
gem 'sprockets-helpers'
gem 'sprockets-sass'
gem 'sass'
gem 'slim'
gem 'crush'
gem 'uglifier'
