source 'http://rubygems.org'

gem 'sinatra'
gem 'sinatra-flash'
gem 'sinatra-contrib'
gem 'sinatra-content-for2'
gem 'pg'
gem 'sequel'
gem 'sequel_pg'
gem 'compass'
gem 'uglifier'
gem 'yui-compressor'
gem 'coffee-script'
gem 'slim'
gem 'mail'